### ISSUE TITLE
Transaction Graphic. Display issue

### ISSUE THREAD

**Issue by OlegMakarenko** [symbol/explorer#1038]
![image](https://user-images.githubusercontent.com/33131259/159712861-8cce60e8-5f76-4757-8255-4a474ebed713.png)
- Account icons is not visible
- Text is not visible in the message popup when presenting JSON

**Comment by cryptoBeliever** [comment]
@AnthonyLaw @OlegMakarenko I think we can close this one. I don't see this bug anymore.
Example: https://testnet.symbol.fyi/transactions/7760A37148EA739679130E4352F2481966B0E11D799A1F1A3C7A086D8786E07B
