### ISSUE TITLE
Details for partial transaction not presented

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/explorer#1105]
Steps to reproduce:

1. Init aggregate bonded that require additional signatures (for example for 2 of 2 multi-sig) and don't sign it.
2. Open partial transaction in explorer:

Result: Transaction details are not visible

https://testnet.symbol.fyi/transactions/6B9E86105ED6968357436EBD2DFF50D925C8D64F7733D2818688DF7EFAA5F740

![image](https://user-images.githubusercontent.com/17684281/188646513-61f9c8c7-45c5-4f31-bf89-e5af3a5e4853.png)

Expected result:
Explorer should present information about the partial transaction. At this moment we can see only related hash lock.

In the console I can see the error:

```
TypeError: Cannot read properties of undefined (reading 'length')
    at Function.l [as fromString] (long.js:221:13)
    at Function.isLongNumericString (UInt64.js:74:33)
    at Function.fromNumericString (UInt64.js:62:21)
    at h (CreateTransactionFromDTO.js:93:137)
    at CreateTransactionFromDTO.js:186:50
    at Array.map (<anonymous>)
    at m (CreateTransactionFromDTO.js:185:55)
    at TransactionHttp.js:50:115
    at l.<anonymous> (Http.js:107:25)
    at Generator.next (<anonymous>)
```

**Comment by AnthonyLaw** [comment]
Due to REST missing the `meta` field from the partial transaction, cause the SDK breaks the explorer.

https://discord.com/channels/856325968096133191/865180563433979904/1016256170996023296
