### ISSUE TITLE
Update UI with latest marketing Iconography 

### ISSUE THREAD

**Issue by JackNEM** [symbol/explorer#762]
Currently, we have a "technical deficit" in the form of both inconsistent and out of date Iconography it would be ideal to update this to the latest marketing standards before version 1 release.

**Comment by JackNEM** [comment]
story point 5 is a very low ball estimate of how long this will take to address @OlegMakarenko feel free to change.

**Comment by AnthonyLaw** [comment]
Related: https://github.com/nemgrouplimited/symbol-explorer/issues/667

**Comment by cryptoBeliever** [comment]
@AnthonyLaw this is still valid or we can close?

**Comment by AnthonyLaw** [comment]
> @AnthonyLaw this is still valid or we can close?

yes, I believe we can close it, those requirements are no longer valid.
