### ISSUE TITLE
Only ONE voting key is shown

### ISSUE THREAD

**Issue by segfaultxavi** [symbol/explorer#848]
Multiple voting keys can be linked to the same account, but explorer only shows one.

Also, it would be nice if the key's period of validity (Start and End Epoch) would be shown along with the linked key.

Extra points awarded if the period of validity is highlighted in red when it is about to expire :)

**Comment by AnthonyLaw** [comment]
do you have an account with a linked multiple voting key?

**Comment by segfaultxavi** [comment]
This account has 3 linked voting keys:
http://explorer.testnet.symboldev.network/accounts/TAZBGUACETXZHAQEQZACFHTLE7OYG2FMGJHZ2SQ

And several Link/Unlink transactions in its history.

**Comment by AnthonyLaw** [comment]
After I checked on the API, it doesn't return multiple Voting key records.

http://api-01.ap-northeast-1.testnet.symboldev.network:3000/accounts/TAZBGUACETXZHAQEQZACFHTLE7OYG2FMGJHZ2SQ

@fboucquez Do we have any endpoint return list of voting key?

**Comment by segfaultxavi** [comment]
I see an array there...
```json
			"voting": {
				"publicKeys": [{
					"publicKey": "45FBCF2F0EA36EFA7923C9BC923D6503169651F7FA4EFC46A8EAF5AE09057EBD",
					"startEpoch": 100,
					"endEpoch": 1000
				}]
			}
```

**Comment by AnthonyLaw** [comment]
I believe this issue had resolved in the `main` branch.

https://symbol.fyi/accounts/NCQG34DBGQAXA7XD2Y3EGFQOASPVRCYMOT6PLIY

![image](https://user-images.githubusercontent.com/5649156/145322738-a548461b-fac7-415f-9972-4740ebcfa46d.png)
