### ISSUE TITLE
testnet timestamp(localtime) vs mainnet timestamp(UTC)

### ISSUE THREAD

**Issue by ryo-opening-line** [symbol/explorer#855]
On the testnet symbol-explorer, the timestamp is showed as localtime(JST) correctly.
It's good to me.

Here's example: 
http://explorer.testnet.symboldev.network/blocks
![image](https://user-images.githubusercontent.com/28587337/112747372-098b9e00-8ff0-11eb-82d6-a348fd6f9078.png)

But the timestamp on the mainnet explorer as same time above is UTC as follows:
It's not good to me.

![image](https://user-images.githubusercontent.com/28587337/112747543-12c93a80-8ff1-11eb-8012-b813b322314b.png)

Could you make the mainnet display the localtime as well as the testnet, please?

The following fixes may have an effect...

https://github.com/nemgrouplimited/symbol-explorer/commit/eae2c24d1a6f496bfac92b5761566c6489e30db5

Could you please check it?

**Comment by AnthonyLaw** [comment]
Thanks to reported that.
Seem the Testnet still used the old version of Explorer. we will update it soon.

We will be the UTC timestamp, to ensure everyone sees the same timestamp.

**Comment by ryo-opening-line** [comment]
Anthony, thank you very much for your confirmation.

Understood that it was an intended fix.
However, I think it is quite confusing because the Explorer of NIS1 was showing the local time as follows.
![image](https://user-images.githubusercontent.com/28587337/112821496-bc77fc80-90c1-11eb-957c-1d731a482bd2.png)

Would it be possible to request an enhancement?

**Comment by AnthonyLaw** [comment]
Will discuss with the team, and let you know :)

**Comment by AnthonyLaw** [comment]
merged [7e24498](https://github.com/symbol/explorer/commit/7e24498ab5d88587032e0aa727a1d0745c89f4d4)
