### ISSUE TITLE
metadata in explorer can be shown as plain text instead of value

### ISSUE THREAD

**Issue by jabo38** [symbol/explorer#909]
the values aren't really human readable which to some extent makes it hard for people looking at an explorer to decipher. The wallet has been able to display the metadata in plain text.  

Here is an example. http://explorer.testnet.symboldev.network/accounts/TBFZX6PSZQYNHHKLABHWYJRMDJSE3CRJOOSSECQ

We can see the meta data is shown as a value. 

![image](https://user-images.githubusercontent.com/10395907/120825913-de5d8780-c527-11eb-8e74-253810af46ea.png)

I could be better to be seen as plain text, not unlike the wallet. 

![image](https://user-images.githubusercontent.com/10395907/120826004-faf9bf80-c527-11eb-9c56-e8c07831e51b.png)

**Comment by cryptoBeliever** [comment]
From wallet version 1.011 metadata values should be consistent in explorer and wallet:

![image](https://user-images.githubusercontent.com/17684281/190929490-6c20644b-204f-4696-b5cf-bc76cbdc0fe6.png)

![image](https://user-images.githubusercontent.com/17684281/190929498-016bc7ab-ed73-45ff-82b3-c931be736e9c.png)
