### ISSUE TITLE
display metadata in explorer for accounts.  

### ISSUE THREAD

**Issue by jabo38** [symbol/explorer#925]
For example. http://explorer.testnet.symboldev.network/accounts/TCWWR5PBTSK4AIEMGSYP72D355AI63NJQ7UL5FA

Has a metadata on it. The explorer shows it as `7B0A224964223A20226469643A61706F7374696C6C65322E302E313A6469722354424243513647424951344E4E58445A4B564B4C4451465933575145464332374A523737593251E2809D2C0A22436F6E74726F6C6C6572223A20226469643A61706F7374696C6C65322E302E313A6164642354415A58334F4545324358365A57564F4A3758465351424845523358493245474D504B4B584559222C0A7D0A`

But in reality it is supposed to be 
`{ "Id": "did:apostille2.0.1:dir#TBBCQ6GBIQ4NNXDZKVKLDQFY3WQEFC27JR77Y2Q”, "Controller": "did:apostille2.0.1:add#TAZX3OEE2CX6ZWVOJ7XFSQBHER3XI2EGMPKKXEY", }`

Here is a screen shot of the explorer which isn't really that human readable
![image](https://user-images.githubusercontent.com/10395907/127904501-692fde9a-26b0-4623-8834-6f708351527a.png)

But here is how it is written in the wallet which makes it a lot easier to decipher. 
![image](https://user-images.githubusercontent.com/10395907/127904669-f8cd003e-6ee7-4d30-8ad7-1e9cf6ce4b1f.png)
And

![image](https://user-images.githubusercontent.com/10395907/127904605-cbcd245b-5854-4ae2-89d4-3a5c7bc6b8ab.png)

Please update to make more readable like the wallet does.

**Comment by jabo38** [comment]
Along with this it would be nice if the the tx itself http://explorer.testnet.symboldev.network/transactions/84456F129528A2960ADE3447653FBFBB3EA7CF6BDA189AD8DDB737DEC21B0EC1 which is a metadata tx can show what the meta is instead of the value, or maybe even show both too is good.

**Comment by cryptoBeliever** [comment]
I think this is because the wallet encodes/decodes metadata on its own. We should define one consistent way to store metadata for our products (and recommended for others).
I've seen that some projects stored it without encoding and in such situation in explorer is presented correctly.

**Comment by jabo38** [comment]
Well that’s interesting. I wasn’t aware the wallet was encoding the metadata.

I agree there should be a standard somehow. It would be really nice if the explorer and wallet followed the same practice.

Generally I’m curious why the wallet was encoding the metadata or maybe it could at least maybe give user a check box to choose encoded or not.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jabo38** [comment]
I have done some more testing and the symbol-cli does indeed announce metadata on chain in a way that the explorer can and does read, which confuses me a bit because then maybe this isn't an explorer issue? 

One has to use the 'symbol-cli converter stringToKey' to take the original text and convert it into a string in the CLI.  Then use that string in the metadata tx and then the explorer can read it. So the explorer can read the CLI but not the wallet, but the wallet can read the wallet, but the explorer can not read the wallet. 

Having the CLI do metadata txs one one and the Desktop wallet do them a different way is confusing for people building the applications. They now have to chose if they want their app to be compatible with the Desktop Wallet or the explorer. 

Any suggestions for a way forward?  I think it is better to make the issue on the Desktop Wallet page as it is the odd app out.

**Comment by jabo38** [comment]
![image](https://user-images.githubusercontent.com/10395907/128404377-89385033-7f52-45f7-afc9-bbc69d637a30.png)

and 

![image](https://user-images.githubusercontent.com/10395907/128404479-4926ba49-9c94-4d2f-a508-0857bca8496a.png)

Clearly makes the test transaction on the explorer clearly able to be ready http://explorer.testnet.symboldev.network/transactions/910AE1C05A9ECD500355F806E9789F6C94516DCE1F9CEE6D114E2CE0B66F643B

![image](https://user-images.githubusercontent.com/10395907/128404749-d5618a8e-f3ab-4dcb-82b5-507646da2686.png)

**Comment by cryptoBeliever** [comment]
As I can see this one is fixed in latest wallet version.
