### ISSUE TITLE
Display is voting node info

### ISSUE THREAD

**Issue by AnthonyLaw** [symbol/explorer#933]
- display is node voting active
- voting key expire info

**Comment by fboucquez** [comment]
Related to https://github.com/symbol/symbol-explorer/issues/907
Expired/Active/Future flag (probably) info + expiring info

**Comment by cryptoBeliever** [comment]
@AnthonyLaw this issue is about "Voting Keys" section in Account view or Node Details View? If the first one we can close it because it's already done:

![image](https://user-images.githubusercontent.com/17684281/190929742-1c3daf7e-7f1d-438e-86d2-4655907327b9.png)

**Comment by AnthonyLaw** [comment]
> @AnthonyLaw this issue is about "Voting Keys" section in Account view or Node Details View? If the first one we can close it because it's already done:
> 
> ![image](https://user-images.githubusercontent.com/17684281/190929742-1c3daf7e-7f1d-438e-86d2-4655907327b9.png)
> 
> If the second one I think may be a duplicate of #934 ?

This Issue is mainly for Node Details View
I will close this one, and we follow up with #934
