### ISSUE TITLE
An error loading a transaction is not properly display

### ISSUE THREAD

**Issue by fboucquez** [symbol/explorer#965]
The exception is ignored and not shown either on the screen or the console.

Example is:

https://symbol.fyi/transactions/2C7FF9B65CE4CAE0B4D2941DB37BBB933E0EA99C815DCD415EAE98CC57E0D11F

2C7FF9B65CE4CAE0B4D2941DB37BBB933E0EA99C815DCD415EAE98CC57E0D11F is an aggregate transaction that includes Mosaic Revocation. The used SDK doesn't support yet which we are fixing now. But the issue is that the exception is eaten, should be logged somewhere.

https://github.com/symbol/symbol-explorer/blob/dev/src/infrastructure/TransactionService.js#L135

You can see that error is not either `console.error` or bubbled up/propagated on the screen. Does explorer have a common exception handling?

Sometimes it's better to don't do anything with the exception that just ignoring it. For example:
Just:
````
	const transactionStatus = await this.getTransactionStatus(hash);
  	const transactionGroup = transactionStatus.message;
  	const transaction = await this.getTransaction(hash, transactionGroup);
  	const [{ timestamp }, effectiveFee] = await Promise.all([
		  BlockService.getBlockInfo(UInt64.fromUint(transaction.transactionInfo.height))
		  	.catch(() => ({ timestamp: null })),
		  this.getTransactionEffectiveFee(hash)
		  	.catch(() => null)
	  ]);
````
Would show the error in the console.
![image](https://user-images.githubusercontent.com/5390558/141513309-d3a8cf39-f421-4e2b-b3e1-1936e381b982.png)

**Comment by fboucquez** [comment]
In case you want to handle 404, the exception handler should check that value

**Comment by AnthonyLaw** [comment]
I verified this issue on the `dev` branch. All seem working great.
I will close this issue now, if anyone found the issue, please reopen it.
